version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-mealapi
    restart: always
    environment:
      POSTGRES_DB: meal_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
